import type { Card } from './types';

export type DeckId = 'balanced' | 'flame' | 'tide' | 'fortress' | 'cavalry' | 'dragon';

export interface DeckProfile {
  id: DeckId;
  name: string;
  summary: string;
}

export const library: Card[] = [
  {
    id: 'ember-scout',
    name: '火花の斥候',
    kind: 'unit',
    element: 'ember',
    cost: 1,
    power: 1200,
    shield: 800,
    text: '召喚時、相手の最前列に500ダメージ。',
    trigger: 'onSummon',
  },
  {
    id: 'ember-scout-vanguard',
    name: '紅槍の先陣',
    kind: 'unit',
    element: 'ember',
    cost: 2,
    power: 1800,
    shield: 1200,
    text: '召喚時、相手の最前列に500ダメージ。',
    trigger: 'onSummon',
  },
  {
    id: 'ember-scout-captain',
    name: '烈火の百将',
    kind: 'unit',
    element: 'ember',
    cost: 3,
    power: 2600,
    shield: 1600,
    text: '召喚時、相手の最前列に500ダメージ。',
    trigger: 'onSummon',
  },
  {
    id: 'tide-adept',
    name: '潮読みの術士',
    kind: 'unit',
    element: 'tide',
    cost: 2,
    power: 1500,
    shield: 1800,
    text: '攻撃時、自分の山札から1枚引く。',
    trigger: 'onAttack',
  },
  {
    id: 'tide-adept-oracle',
    name: '蒼河の参謀',
    kind: 'unit',
    element: 'tide',
    cost: 3,
    power: 1700,
    shield: 2400,
    text: '攻撃時、自分の山札から1枚引く。',
    trigger: 'onAttack',
  },
  {
    id: 'tide-adept-admiral',
    name: '水軍の都督',
    kind: 'unit',
    element: 'tide',
    cost: 4,
    power: 2600,
    shield: 2800,
    text: '攻撃時、自分の山札から1枚引く。',
    trigger: 'onAttack',
  },
  {
    id: 'terra-warden',
    name: '樹殻の守護者',
    kind: 'unit',
    element: 'terra',
    cost: 2,
    power: 800,
    shield: 3000,
    text: '高い耐久でシールドを守る。',
  },
  {
    id: 'terra-warden-wall',
    name: '城門の巨盾',
    kind: 'unit',
    element: 'terra',
    cost: 3,
    power: 1000,
    shield: 4200,
    text: '高い耐久でシールドを守る。',
  },
  {
    id: 'terra-warden-general',
    name: '翠甲の守将',
    kind: 'unit',
    element: 'terra',
    cost: 4,
    power: 2200,
    shield: 5200,
    text: '高い耐久でシールドを守る。',
  },
  {
    id: 'volt-runner',
    name: '閃走の機士',
    kind: 'unit',
    element: 'volt',
    cost: 3,
    power: 2500,
    shield: 1200,
    text: '召喚したターンから攻撃できる。',
  },
  {
    id: 'volt-runner-lancer',
    name: '雷槍の騎兵',
    kind: 'unit',
    element: 'volt',
    cost: 2,
    power: 2000,
    shield: 1000,
    text: '召喚したターンから攻撃できる。',
  },
  {
    id: 'volt-runner-commander',
    name: '金雷の将軍',
    kind: 'unit',
    element: 'volt',
    cost: 4,
    power: 3600,
    shield: 2200,
    text: '召喚したターンから攻撃できる。',
  },
  {
    id: 'void-dragon',
    name: '黒星の竜',
    kind: 'unit',
    element: 'void',
    cost: 5,
    power: 5000,
    shield: 5000,
    text: '進化元がいるレーンに出すとコスト-2。',
    evolution: 'any',
  },
  {
    id: 'void-dragon-eclipse',
    name: '蝕星の黒龍',
    kind: 'unit',
    element: 'void',
    cost: 6,
    power: 6500,
    shield: 6000,
    text: '進化元がいるレーンに出すとコスト-2。',
    evolution: 'any',
  },
  {
    id: 'void-dragon-emperor',
    name: '黒天の覇龍',
    kind: 'unit',
    element: 'void',
    cost: 7,
    power: 8000,
    shield: 7000,
    text: '進化元がいるレーンに出すとコスト-2。',
    evolution: 'any',
  },
  {
    id: 'ember-burst',
    name: '紅蓮の一撃',
    kind: 'spell',
    element: 'ember',
    cost: 2,
    power: 2000,
    shield: 0,
    text: '選んだ敵ユニットに2000ダメージ。いなければ相手HPに1000ダメージ。',
  },
  {
    id: 'ember-burst-volley',
    name: '火矢斉射',
    kind: 'spell',
    element: 'ember',
    cost: 3,
    power: 2600,
    shield: 0,
    text: '選んだ敵ユニットに2600ダメージ。いなければ相手HPに1000ダメージ。',
  },
  {
    id: 'ember-burst-inferno',
    name: '業火の号令',
    kind: 'spell',
    element: 'ember',
    cost: 4,
    power: 3600,
    shield: 0,
    text: '選んだ敵ユニットに3600ダメージ。いなければ相手HPに1000ダメージ。',
  },
  {
    id: 'tide-recall',
    name: '還流の印',
    kind: 'spell',
    element: 'tide',
    cost: 3,
    power: 0,
    shield: 0,
    text: 'カードを2枚引く。',
  },
  {
    id: 'tide-recall-map',
    name: '水図の読解',
    kind: 'spell',
    element: 'tide',
    cost: 2,
    power: 0,
    shield: 0,
    text: 'カードを2枚引く。',
  },
  {
    id: 'tide-recall-grand',
    name: '大河の兵法',
    kind: 'spell',
    element: 'tide',
    cost: 4,
    power: 0,
    shield: 0,
    text: 'カードを2枚引く。',
  },
  {
    id: 'terra-root',
    name: '大樹の契約',
    kind: 'spell',
    element: 'terra',
    cost: 1,
    power: 0,
    shield: 0,
    text: 'このターンのマナを2増やす。',
  },
  {
    id: 'terra-root-supply',
    name: '兵糧の補給路',
    kind: 'spell',
    element: 'terra',
    cost: 2,
    power: 0,
    shield: 0,
    text: 'このターンのマナを2増やす。',
  },
  {
    id: 'terra-root-fortify',
    name: '城塞の築造',
    kind: 'spell',
    element: 'terra',
    cost: 3,
    power: 0,
    shield: 0,
    text: 'このターンのマナを2増やす。',
  },
  {
    id: 'mirror-trap',
    name: '反鏡の罠',
    kind: 'trap',
    element: 'void',
    cost: 2,
    power: 1500,
    shield: 0,
    text: '次に自分が攻撃された時、攻撃ユニットに1500ダメージ。',
  },
  {
    id: 'mirror-trap-ambush',
    name: '伏兵の反鏡',
    kind: 'trap',
    element: 'void',
    cost: 3,
    power: 2200,
    shield: 0,
    text: '次に自分が攻撃された時、攻撃ユニットに2200ダメージ。',
  },
  {
    id: 'mirror-trap-grand',
    name: '紫電の包囲陣',
    kind: 'trap',
    element: 'void',
    cost: 4,
    power: 3200,
    shield: 0,
    text: '次に自分が攻撃された時、攻撃ユニットに3200ダメージ。',
  },
];

export const deckCatalog: DeckProfile[] = [
  { id: 'balanced', name: '王道軍', summary: '攻防の標準型' },
  { id: 'flame', name: '火矢軍', summary: '速攻と火力' },
  { id: 'tide', name: '水軍策士', summary: '手札補充重視' },
  { id: 'fortress', name: '城塞守備', summary: '高HPで耐える' },
  { id: 'cavalry', name: '雷騎突撃', summary: '速攻武将中心' },
  { id: 'dragon', name: '黒龍覇道', summary: '大型進化狙い' },
];

const deckLists: Record<DeckId, string[]> = {
  balanced: [
    'ember-scout',
    'ember-scout-vanguard',
    'tide-adept',
    'tide-adept-oracle',
    'terra-warden',
    'terra-warden-wall',
    'volt-runner',
    'volt-runner-lancer',
    'void-dragon',
    'ember-burst',
    'ember-burst-volley',
    'tide-recall',
    'terra-root',
    'terra-root-supply',
    'mirror-trap',
    'mirror-trap-ambush',
  ],
  flame: [
    'ember-scout',
    'ember-scout-vanguard',
    'ember-scout-captain',
    'volt-runner',
    'volt-runner-lancer',
    'terra-warden',
    'void-dragon',
    'ember-burst',
    'ember-burst-volley',
    'ember-burst-inferno',
    'terra-root',
    'terra-root-supply',
    'tide-recall',
    'mirror-trap',
    'mirror-trap-ambush',
    'mirror-trap-grand',
  ],
  tide: [
    'tide-adept',
    'tide-adept-oracle',
    'tide-adept-admiral',
    'terra-warden',
    'terra-warden-wall',
    'ember-scout',
    'volt-runner',
    'void-dragon',
    'tide-recall',
    'tide-recall-map',
    'tide-recall-grand',
    'ember-burst',
    'terra-root',
    'mirror-trap',
    'mirror-trap-ambush',
    'mirror-trap-grand',
  ],
  fortress: [
    'terra-warden',
    'terra-warden-wall',
    'terra-warden-general',
    'tide-adept',
    'tide-adept-oracle',
    'ember-scout',
    'void-dragon',
    'void-dragon-eclipse',
    'terra-root',
    'terra-root-supply',
    'terra-root-fortify',
    'tide-recall',
    'ember-burst',
    'mirror-trap',
    'mirror-trap-ambush',
    'mirror-trap-grand',
  ],
  cavalry: [
    'volt-runner',
    'volt-runner-lancer',
    'volt-runner-commander',
    'ember-scout',
    'ember-scout-vanguard',
    'tide-adept',
    'terra-warden',
    'void-dragon',
    'ember-burst',
    'ember-burst-volley',
    'terra-root',
    'terra-root-supply',
    'tide-recall',
    'mirror-trap',
    'mirror-trap-ambush',
    'mirror-trap-grand',
  ],
  dragon: [
    'void-dragon',
    'void-dragon-eclipse',
    'void-dragon-emperor',
    'terra-warden',
    'terra-warden-general',
    'tide-adept',
    'tide-adept-admiral',
    'ember-scout',
    'terra-root',
    'terra-root-supply',
    'terra-root-fortify',
    'tide-recall',
    'tide-recall-grand',
    'ember-burst-inferno',
    'mirror-trap-ambush',
    'mirror-trap-grand',
  ],
};

export function buildStarterDeck(deckId: DeckId = 'balanced'): Card[] {
  const ids = deckLists[deckId];

  return ids.map((id, index) => ({
    ...library.find((card) => card.id === id)!,
    id: `${id}-${index}`,
  }));
}

export const elementLabel: Record<Card['element'], string> = {
  ember: '火',
  tide: '水',
  terra: '森',
  volt: '雷',
  void: '虚',
};

export const elementBeats: Record<Card['element'], Card['element']> = {
  ember: 'terra',
  terra: 'volt',
  volt: 'tide',
  tide: 'ember',
  void: 'void',
};
